version: '3.8'
#containers => services
services:
  mysql-springboot-container:
    image: mysql:8.0.28
    container_name: mysql-springboot-container
    ports:
      - 3333:3306
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: lilo4801
      MYSQL_PASSWORD: Abc@123456
      MYSQL_ROOT_PASSWORD: Abc@123456
      MYSQL_DATABASE: Tiktok
  springboot-docker-container:
    image: lilo4801/springboot-docker:v1.0.0.0
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - app-logs:/app/logs
      - images:/app/images
    networks:
      - backend
#create network
networks:
  backend:
    name: springboot-app-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:
  app-logs:
  images: