version: '2.1'
#containers => services
services:
  mysql-springboot-container:
    image: mysql:8.0.28
    container_name: mysql-springboot-container
    ports:
      - 3333:3306
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: lilo4801
      MYSQL_PASSWORD: Abc@123456
      MYSQL_ROOT_PASSWORD: Abc@123456
      MYSQL_DATABASE: Tiktok
  springboot-docker-container:
    build:
      context: .
      dockerfile: Dockerfile_debug
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    volumes:
      - app-logs:/app/logs
      - images:/app/images
    networks:
      - backend
    command: java -Djava.security.egd=file:/dev/./urandom -jar tiktok-0.0.1-SNAPSHOT.jar
#create network
networks:
  backend:
    name: springboot-app-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:
  app-logs:
  images:
