# Stage 1: Build the application
FROM maven:3.5.4-jdk-8 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests

# Stage 2: Create a new image with the updated JAR file
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/target/tiktok-0.0.1-SNAPSHOT.jar .

